# frozen_string_literal: true

require "fileutils"
require "time"

module Aidp
  module Init
    # Generates provider-specific agent instruction files that direct agents to
    # project style guides and provide context about the project.
    class ProviderInstructionGenerator
      def initialize(project_dir = Dir.pwd)
        @project_dir = project_dir
      end

      # Generate instruction files for all available providers
      #
      # @param analysis [Hash] Project analysis data
      # @param preferences [Hash] User preferences from init
      # @return [Array<String>] List of generated file paths
      def generate(analysis:, preferences: {})
        Aidp.log_debug("provider_instruction_generator", "generate", project_dir: @project_dir)

        generated_files = []
        available_providers.each do |provider_class|
          path = provider_class.instruction_file_path
          next unless path

          full_path = File.join(@project_dir, path)
          ensure_parent_directory(full_path)

          content = generate_instruction_content(
            provider_class: provider_class,
            analysis: analysis,
            preferences: preferences
          )

          File.write(full_path, content)
          generated_files << path

          Aidp.log_info(
            "provider_instruction_generator",
            "generated_file",
            provider: provider_class.name,
            path: path
          )
        end

        generated_files
      end

      private

      # Get all available provider classes
      def available_providers
        require_relative "../providers/anthropic"
        require_relative "../providers/cursor"
        require_relative "../providers/github_copilot"
        require_relative "../providers/gemini"
        require_relative "../providers/kilocode"
        require_relative "../providers/aider"
        require_relative "../providers/codex"
        require_relative "../providers/opencode"

        [
          Aidp::Providers::Anthropic,
          Aidp::Providers::Cursor,
          Aidp::Providers::GithubCopilot,
          Aidp::Providers::Gemini,
          Aidp::Providers::Kilocode,
          Aidp::Providers::Aider,
          Aidp::Providers::Codex,
          Aidp::Providers::Opencode
        ]
      end

      # Ensure parent directory exists for a file path
      def ensure_parent_directory(file_path)
        parent_dir = File.dirname(file_path)
        FileUtils.mkdir_p(parent_dir) unless Dir.exist?(parent_dir)
      end

      # Generate instruction file content for a provider
      def generate_instruction_content(provider_class:, analysis:, preferences:)
        project_name = extract_project_name
        languages = analysis[:languages].keys.join(", ")
        frameworks = extract_confident_names(analysis[:frameworks])
        frameworks_text = frameworks.empty? ? "None detected" : frameworks.join(", ")

        <<~INSTRUCTIONS
          # AI Agent Instructions for #{project_name}

          > Generated by `aidp init` on #{Time.now.utc.iso8601}
          > Provider: #{provider_class.name}

          ## 🎯 Most Important: Check the Project Style Guide

          **Before making ANY code changes, you MUST read and follow [`docs/LLM_STYLE_GUIDE.md`](docs/LLM_STYLE_GUIDE.md).**

          This file contains:
          - Project-specific coding conventions and patterns
          - Testing guidelines and framework usage
          - Code organization principles
          - Error handling and logging standards
          - Performance and security best practices

          ## About This Project

          **Project Name**: #{project_name}

          **Languages**: #{languages}

          **Frameworks**: #{frameworks_text}

          **Key Documentation**:
          - [`docs/LLM_STYLE_GUIDE.md`](docs/LLM_STYLE_GUIDE.md) - Primary reference for AI agents
          - [`docs/PROJECT_ANALYSIS.md`](docs/PROJECT_ANALYSIS.md) - Repository structure and analysis
          - [`docs/CODE_QUALITY_PLAN.md`](docs/CODE_QUALITY_PLAN.md) - Quality improvement roadmap
          - [`README.md`](README.md) - Project overview and setup

          ## Working with This Project

          1. **Read the style guide first** - It's tailored to this project's conventions
          2. **Follow existing patterns** - Look at similar code before adding new features
          3. **Test your changes** - Use the project's testing framework
          4. **Document significant changes** - Update relevant documentation

          ## Quick Reference

          ### Code Style
          - Refer to `docs/LLM_STYLE_GUIDE.md` for detailed conventions
          - Follow the project's existing naming patterns
          - Keep methods small and focused
          - Use dependency injection for testability

          ### Testing
          - Tests are located in the project's test directories
          - Run tests before committing changes
          - Add tests for new functionality

          ### Common Commands
          Check `README.md` for project-specific commands and setup instructions.

          ---

          **Remember**: Always consult `docs/LLM_STYLE_GUIDE.md` before making code changes!
        INSTRUCTIONS
      end

      # Extract project name from directory or git config
      def extract_project_name
        # Try git config first
        if Dir.exist?(File.join(@project_dir, ".git"))
          begin
            require "open3"
            output, status = Open3.capture2("git", "config", "--get", "remote.origin.url", chdir: @project_dir)
            if status.success? && !output.empty?
              # Extract name from git URL (e.g., "owner/repo.git" -> "repo")
              match = output.match(%r{/([^/]+?)(?:\.git)?$})
              return match[1] if match
            end
          rescue
            # Fall through to directory name
          end
        end

        # Fallback to directory name
        File.basename(@project_dir)
      end

      # Extract confident framework names
      def extract_confident_names(detections, threshold: 0.7)
        return [] if detections.nil? || detections.empty?

        detections
          .select { |d| d[:confidence] >= threshold }
          .map { |d| d[:name] }
      end
    end
  end
end
