name: Coverage Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: coverage-badge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Run coverage tasks
        run: |
          bundle exec rake coverage:run coverage:summary

      - name: Commit updated coverage badge (main only if changed)
        if: github.ref == 'refs/heads/main'
        run: |
          if git diff --quiet badges/coverage.svg; then
            echo 'Coverage badge unchanged; no commit.'
          else
            git config user.name 'coverage-bot'
            git config user.email 'coverage-bot@users.noreply.github.com'
            git add badges/coverage.svg coverage/ratchet.json coverage/summary.json || true
            git commit -m 'chore: update coverage badge [skip ci]' || echo 'Nothing to commit'
            git push
          fi
