name: Coverage Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: coverage-badge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Run coverage tasks
        run: |
          bundle exec rake coverage:run coverage:summary

      - name: Commit updated coverage badge (main only if changed)
        if: github.ref == 'refs/heads/main'
        run: |
          if git diff --quiet badges/coverage.svg; then
            echo 'Coverage badge unchanged; no commit.'
          else
            git config user.name 'coverage-bot'
            git config user.email 'coverage-bot@users.noreply.github.com'
            git add badges/coverage.svg coverage/ratchet.json coverage/summary.json || true
            git commit -m 'chore: update coverage badge [skip ci]' || echo 'Nothing to commit'
            git push
          fi
