name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: ruby
          package-name: aidp
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          default-branch: main
